require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionairreItemsController do

  # This should return the minimal set of attributes required to create a valid
  # QuestionairreItem. As you add validations to QuestionairreItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all questionairre_items as @questionairre_items" do
      questionairre_item = QuestionairreItem.create! valid_attributes
      get :index
      assigns(:questionairre_items).should eq([questionairre_item])
    end
  end

  describe "GET show" do
    it "assigns the requested questionairre_item as @questionairre_item" do
      questionairre_item = QuestionairreItem.create! valid_attributes
      get :show, :id => questionairre_item.id.to_s
      assigns(:questionairre_item).should eq(questionairre_item)
    end
  end

  describe "GET new" do
    it "assigns a new questionairre_item as @questionairre_item" do
      get :new
      assigns(:questionairre_item).should be_a_new(QuestionairreItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested questionairre_item as @questionairre_item" do
      questionairre_item = QuestionairreItem.create! valid_attributes
      get :edit, :id => questionairre_item.id.to_s
      assigns(:questionairre_item).should eq(questionairre_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuestionairreItem" do
        expect {
          post :create, :questionairre_item => valid_attributes
        }.to change(QuestionairreItem, :count).by(1)
      end

      it "assigns a newly created questionairre_item as @questionairre_item" do
        post :create, :questionairre_item => valid_attributes
        assigns(:questionairre_item).should be_a(QuestionairreItem)
        assigns(:questionairre_item).should be_persisted
      end

      it "redirects to the created questionairre_item" do
        post :create, :questionairre_item => valid_attributes
        response.should redirect_to(QuestionairreItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questionairre_item as @questionairre_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionairreItem.any_instance.stub(:save).and_return(false)
        post :create, :questionairre_item => {}
        assigns(:questionairre_item).should be_a_new(QuestionairreItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionairreItem.any_instance.stub(:save).and_return(false)
        post :create, :questionairre_item => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questionairre_item" do
        questionairre_item = QuestionairreItem.create! valid_attributes
        # Assuming there are no other questionairre_items in the database, this
        # specifies that the QuestionairreItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuestionairreItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => questionairre_item.id, :questionairre_item => {'these' => 'params'}
      end

      it "assigns the requested questionairre_item as @questionairre_item" do
        questionairre_item = QuestionairreItem.create! valid_attributes
        put :update, :id => questionairre_item.id, :questionairre_item => valid_attributes
        assigns(:questionairre_item).should eq(questionairre_item)
      end

      it "redirects to the questionairre_item" do
        questionairre_item = QuestionairreItem.create! valid_attributes
        put :update, :id => questionairre_item.id, :questionairre_item => valid_attributes
        response.should redirect_to(questionairre_item)
      end
    end

    describe "with invalid params" do
      it "assigns the questionairre_item as @questionairre_item" do
        questionairre_item = QuestionairreItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionairreItem.any_instance.stub(:save).and_return(false)
        put :update, :id => questionairre_item.id.to_s, :questionairre_item => {}
        assigns(:questionairre_item).should eq(questionairre_item)
      end

      it "re-renders the 'edit' template" do
        questionairre_item = QuestionairreItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionairreItem.any_instance.stub(:save).and_return(false)
        put :update, :id => questionairre_item.id.to_s, :questionairre_item => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questionairre_item" do
      questionairre_item = QuestionairreItem.create! valid_attributes
      expect {
        delete :destroy, :id => questionairre_item.id.to_s
      }.to change(QuestionairreItem, :count).by(-1)
    end

    it "redirects to the questionairre_items list" do
      questionairre_item = QuestionairreItem.create! valid_attributes
      delete :destroy, :id => questionairre_item.id.to_s
      response.should redirect_to(questionairre_items_url)
    end
  end

end
