require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionnaireGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # QuestionnaireGroup. As you add validations to QuestionnaireGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all questionnaire_groups as @questionnaire_groups" do
      questionnaire_group = QuestionnaireGroup.create! valid_attributes
      get :index
      assigns(:questionnaire_groups).should eq([questionnaire_group])
    end
  end

  describe "GET show" do
    it "assigns the requested questionnaire_group as @questionnaire_group" do
      questionnaire_group = QuestionnaireGroup.create! valid_attributes
      get :show, :id => questionnaire_group.id.to_s
      assigns(:questionnaire_group).should eq(questionnaire_group)
    end
  end

  describe "GET new" do
    it "assigns a new questionnaire_group as @questionnaire_group" do
      get :new
      assigns(:questionnaire_group).should be_a_new(QuestionnaireGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested questionnaire_group as @questionnaire_group" do
      questionnaire_group = QuestionnaireGroup.create! valid_attributes
      get :edit, :id => questionnaire_group.id.to_s
      assigns(:questionnaire_group).should eq(questionnaire_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuestionnaireGroup" do
        expect {
          post :create, :questionnaire_group => valid_attributes
        }.to change(QuestionnaireGroup, :count).by(1)
      end

      it "assigns a newly created questionnaire_group as @questionnaire_group" do
        post :create, :questionnaire_group => valid_attributes
        assigns(:questionnaire_group).should be_a(QuestionnaireGroup)
        assigns(:questionnaire_group).should be_persisted
      end

      it "redirects to the created questionnaire_group" do
        post :create, :questionnaire_group => valid_attributes
        response.should redirect_to(QuestionnaireGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questionnaire_group as @questionnaire_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionnaireGroup.any_instance.stub(:save).and_return(false)
        post :create, :questionnaire_group => {}
        assigns(:questionnaire_group).should be_a_new(QuestionnaireGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionnaireGroup.any_instance.stub(:save).and_return(false)
        post :create, :questionnaire_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questionnaire_group" do
        questionnaire_group = QuestionnaireGroup.create! valid_attributes
        # Assuming there are no other questionnaire_groups in the database, this
        # specifies that the QuestionnaireGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuestionnaireGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => questionnaire_group.id, :questionnaire_group => {'these' => 'params'}
      end

      it "assigns the requested questionnaire_group as @questionnaire_group" do
        questionnaire_group = QuestionnaireGroup.create! valid_attributes
        put :update, :id => questionnaire_group.id, :questionnaire_group => valid_attributes
        assigns(:questionnaire_group).should eq(questionnaire_group)
      end

      it "redirects to the questionnaire_group" do
        questionnaire_group = QuestionnaireGroup.create! valid_attributes
        put :update, :id => questionnaire_group.id, :questionnaire_group => valid_attributes
        response.should redirect_to(questionnaire_group)
      end
    end

    describe "with invalid params" do
      it "assigns the questionnaire_group as @questionnaire_group" do
        questionnaire_group = QuestionnaireGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionnaireGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => questionnaire_group.id.to_s, :questionnaire_group => {}
        assigns(:questionnaire_group).should eq(questionnaire_group)
      end

      it "re-renders the 'edit' template" do
        questionnaire_group = QuestionnaireGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionnaireGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => questionnaire_group.id.to_s, :questionnaire_group => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questionnaire_group" do
      questionnaire_group = QuestionnaireGroup.create! valid_attributes
      expect {
        delete :destroy, :id => questionnaire_group.id.to_s
      }.to change(QuestionnaireGroup, :count).by(-1)
    end

    it "redirects to the questionnaire_groups list" do
      questionnaire_group = QuestionnaireGroup.create! valid_attributes
      delete :destroy, :id => questionnaire_group.id.to_s
      response.should redirect_to(questionnaire_groups_url)
    end
  end

end
