require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VendorQuestionnaireAssignmentsController do

  # This should return the minimal set of attributes required to create a valid
  # VendorQuestionnaireAssignment. As you add validations to VendorQuestionnaireAssignment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all vendor_questionnaire_assignments as @vendor_questionnaire_assignments" do
      vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
      get :index
      assigns(:vendor_questionnaire_assignments).should eq([vendor_questionnaire_assignment])
    end
  end

  describe "GET show" do
    it "assigns the requested vendor_questionnaire_assignment as @vendor_questionnaire_assignment" do
      vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
      get :show, :id => vendor_questionnaire_assignment.id.to_s
      assigns(:vendor_questionnaire_assignment).should eq(vendor_questionnaire_assignment)
    end
  end

  describe "GET new" do
    it "assigns a new vendor_questionnaire_assignment as @vendor_questionnaire_assignment" do
      get :new
      assigns(:vendor_questionnaire_assignment).should be_a_new(VendorQuestionnaireAssignment)
    end
  end

  describe "GET edit" do
    it "assigns the requested vendor_questionnaire_assignment as @vendor_questionnaire_assignment" do
      vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
      get :edit, :id => vendor_questionnaire_assignment.id.to_s
      assigns(:vendor_questionnaire_assignment).should eq(vendor_questionnaire_assignment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VendorQuestionnaireAssignment" do
        expect {
          post :create, :vendor_questionnaire_assignment => valid_attributes
        }.to change(VendorQuestionnaireAssignment, :count).by(1)
      end

      it "assigns a newly created vendor_questionnaire_assignment as @vendor_questionnaire_assignment" do
        post :create, :vendor_questionnaire_assignment => valid_attributes
        assigns(:vendor_questionnaire_assignment).should be_a(VendorQuestionnaireAssignment)
        assigns(:vendor_questionnaire_assignment).should be_persisted
      end

      it "redirects to the created vendor_questionnaire_assignment" do
        post :create, :vendor_questionnaire_assignment => valid_attributes
        response.should redirect_to(VendorQuestionnaireAssignment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vendor_questionnaire_assignment as @vendor_questionnaire_assignment" do
        # Trigger the behavior that occurs when invalid params are submitted
        VendorQuestionnaireAssignment.any_instance.stub(:save).and_return(false)
        post :create, :vendor_questionnaire_assignment => {}
        assigns(:vendor_questionnaire_assignment).should be_a_new(VendorQuestionnaireAssignment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VendorQuestionnaireAssignment.any_instance.stub(:save).and_return(false)
        post :create, :vendor_questionnaire_assignment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vendor_questionnaire_assignment" do
        vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
        # Assuming there are no other vendor_questionnaire_assignments in the database, this
        # specifies that the VendorQuestionnaireAssignment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VendorQuestionnaireAssignment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => vendor_questionnaire_assignment.id, :vendor_questionnaire_assignment => {'these' => 'params'}
      end

      it "assigns the requested vendor_questionnaire_assignment as @vendor_questionnaire_assignment" do
        vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
        put :update, :id => vendor_questionnaire_assignment.id, :vendor_questionnaire_assignment => valid_attributes
        assigns(:vendor_questionnaire_assignment).should eq(vendor_questionnaire_assignment)
      end

      it "redirects to the vendor_questionnaire_assignment" do
        vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
        put :update, :id => vendor_questionnaire_assignment.id, :vendor_questionnaire_assignment => valid_attributes
        response.should redirect_to(vendor_questionnaire_assignment)
      end
    end

    describe "with invalid params" do
      it "assigns the vendor_questionnaire_assignment as @vendor_questionnaire_assignment" do
        vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VendorQuestionnaireAssignment.any_instance.stub(:save).and_return(false)
        put :update, :id => vendor_questionnaire_assignment.id.to_s, :vendor_questionnaire_assignment => {}
        assigns(:vendor_questionnaire_assignment).should eq(vendor_questionnaire_assignment)
      end

      it "re-renders the 'edit' template" do
        vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VendorQuestionnaireAssignment.any_instance.stub(:save).and_return(false)
        put :update, :id => vendor_questionnaire_assignment.id.to_s, :vendor_questionnaire_assignment => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vendor_questionnaire_assignment" do
      vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
      expect {
        delete :destroy, :id => vendor_questionnaire_assignment.id.to_s
      }.to change(VendorQuestionnaireAssignment, :count).by(-1)
    end

    it "redirects to the vendor_questionnaire_assignments list" do
      vendor_questionnaire_assignment = VendorQuestionnaireAssignment.create! valid_attributes
      delete :destroy, :id => vendor_questionnaire_assignment.id.to_s
      response.should redirect_to(vendor_questionnaire_assignments_url)
    end
  end

end
